/* Generated by Together */

package com.progdan.edmis.control.users;

import java.sql.*;
import java.util.Vector;

import com.progdan.logengine.*;
import com.progdan.edmis.control.database.*;
import com.progdan.edmis.model.user.User;

public class NewUsersController {
    private static Logger logger = Logger.getLogger(NewUsersController.class.
            getName());
    public static NewUsersController getInstance() {
        logger.debug(">>> Start of NewUsersController.getInstance()***");
        if (instance == null) {
            instance = new com.progdan.edmis.control.users.NewUsersController();
        }
        logger.debug("<<< End of NewUsersController.getInstance()***");
        return instance;
    }

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Singleton
     * @supplierRole Singleton factory
     */
    /*# private NewUsersController _newUsersController; */
    private static NewUsersController instance = null;

    public Vector getNewUsers(User user) {
        logger.debug(">>> Start of NewUsersController.getNewUsers()***");
        Vector newusers = new Vector();
        DatabaseController bd = user.getBd();
        Connection conn = user.getConn();
        String sql = "SELECT UserLogin FROM Users WHERE UserRegister >= DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) ORDER BY UserLogin";
        ResultSet rs = bd.executeQuery(conn, sql);
        try{
            while (rs.next()) {
                newusers.add(rs.getString("UserLogin"));
            }
        }catch(SQLException e){
            logger.error(e);
        }
        logger.debug("<<< End of NewUsersController.getNewUsers()***");
        return newusers;
    }
}
