/* Generated by Together */

package com.progdan.edmis.control.users;

import java.sql.*;
import java.util.Vector;

import com.progdan.logengine.*;
import com.progdan.edmis.control.database.*;
import com.progdan.edmis.model.user.User;

public class OnlineUsersController {
    private static Logger logger = Logger.getLogger(OnlineUsersController.class.
            getName());

    public static OnlineUsersController getInstance() {
        logger.debug(">>> Start of OnlineUsersController.getInstance()***");
        if (instance == null) {
            instance = new OnlineUsersController();
        }
        logger.debug("<<< End of OnlineUsersController.getInstance()***");
        return instance;
    }

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Singleton
     * @supplierRole Singleton factory
     */
    /*# private OnlineUsersController _onlineUsersController; */
    private static OnlineUsersController instance = null;

    public Vector getOnlineUsers(User user) {
        logger.debug(">>> Start of OnlineUsersController.getOnlineUsers()***");
        DatabaseController bd = user.getBd();
        Connection conn = user.getConn();
        Vector online = new Vector();
        String sql = "SELECT UserLogin FROM Users WHERE UserActive=1 ORDER BY UserLogin";
        ResultSet rs = bd.executeQuery(conn, sql);
        try {
            while (rs.next()) {
                online.add(rs.getString("UserLogin"));
            }
        } catch (SQLException e) {
            logger.error(e);
        }
        logger.debug("<<< End of OnlineUsersController.getOnlineUsers()***");
        return online;
    }

}
